const wisdom = [
  "WISDOM IS THE OFFSPRING OF SUFFERING AND TIME",
  "SLOWNESS LENDS STRENGTH TO ONE'S ENEMIES",
  "TO ENTERTAIN DOUBT IS TO DANCE WITH DEATH",
  "THERE IS A FINE LINE BETWEEN CONSIDERATION AND HESITATION. THE FORMER IS WISDOM, THE LATTER IS FEAR",
  "WHERE THERE IS A SILVER KEY, THERE MUST BE A SILVER DOOR",
  "WHERE THERE IS A GOLDEN KEY, THERE MUST BE A GOLDEN DOOR",
  "GOLD IS THE MOST LIBERATING OF METALS",
  "THE LAST EMPEROR IS ALWAYS THE WORST",
  "AN EMPEROR MUST KNOW PRECISELY WHERE HE STANDS",
  "THE ESSENCE OF AN EMPIRE MUST BE SHARED EQUALLY AMONGST ALL OF ITS CITIZENS",
  "SOME THINGS THAT SLUMBER SHOULD NEVER BE AWOKEN",
  "AN EMPEROR IS ONLY AS EFFICIENT AS THOSE HE COMMANDS",
  "IT IS THE SOVEREIGN WHO EMPOWERS THE SCEPTRE. NOT THE OTHER WAY ROUND",
  "AN EMPEROR MUST WEAR TWO BLADES: HOPE IN THE LEFT HAND, SURETY IN THE RIGHT",
  "BELIEF IS THE STRONGEST METAL OF THEM ALL",
  "AN ASPIRANT CAN AFFORD TO BE PROMISING. AN EMPEROR MUST KEEP THOSE PROMISES",
  "THE THRONE IS THE MOST DEVIOUS TRAP OF THEM ALL",
  "MISERY LOVES COMPANY I SUPPOSE"
]

exports.Quotes = wisdom;
